categories:
- Gene clustering
- Genome comparison
description: Efficient inference of large prokaryotic pangenomes with PanTA.
long_description: |
   To Do
   
   https://github.com/amromics/panta
name: panta
owner: Le, D.Q., Nguyen, T.A., Nguyen, S.H. et al
remote_repository_url: https://github.com/amromics/panta
homepage_url: https://github.com/amromics/panta
type: unrestricted